### ISSUE TITLE
add support for iam roles for tasks

### ISSUE THREAD

**Issue by jonnymacs** [noppoMan/aws-sdk-swift-core#21]
Hi Yuki,

When running as an ecs task, a docker container can be granted aws privileges that the host instance does not have. For example the container can be granted kinesis putRecord privileges while the host instance does not have this privilege.

See https://aws.amazon.com/about-aws/whats-new/2016/07/amazon-ec2-container-service-now-supports-iam-roles-for-tasks/

Support for accessing container level privileges is documented here

http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html

I believe it would be an enhancement to the MetaDataService. But Query 169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI which returns

```
{
    "AccessKeyId": "ACCESS_KEY_ID",
    "Expiration": "EXPIRATION_DATE",
    "RoleArn": "TASK_ROLE_ARN",
    "SecretAccessKey": "SECRET_ACCESS_KEY",
    "Token": "SECURITY_TOKEN_STRING"
}
```

Note this api does not return everything that the instance metadata query returns.  Code, LastUpdated, and Type are not returned.

Let me know your thoughts on it?

**Comment by jonnymacs** [comment]
@noppoMan I have spent some time on this enhancement, but I've run into an issue I am struggling to debug. You can see my code change to the metadata service on the referenced branch.

I do not know why, but the http get request to 169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI  with the prorsum HTTPClient returns a 400 error. I cannot figure out why. 

The best I've been able to do is print an error thrown in the call to `let message = try parser.parse(stream.read(upTo: 2948)).first` [here](https://github.com/noppoMan/Prorsum/blob/master/Sources/Prorsum/HTTP/HTTPClient.swift#L11)  But the error is cryptic and vague: `data received after completed connection: close message`

I am able to see call is registered as a 400 response code in the audit logs on the ec2 instance. What stands out is a missing value from [this list](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/logs.html#task_iam_roles-logs) . The missing value is `The task ARN that the requesting container belongs to`

A few more pieces of information that might be useful - 

- When I test the call to the instance metadata url 169.254.169.254/latest/meta-data/iam/security-credentials/, I get a 200 and the expected json. I can also successfully call google.com as referenced in your [example here](https://github.com/noppoMan/Prorsum#httphttps-client)
- I am able to call the 169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI  successfully using the vapor engine HTTP Client from my vapor Droplet config setup function. I do not know what is different about calling the service using that client from this other part of my code.

I will continue trying to figure this out, but any insight is very much appreciated.

**Comment by jonnymacs** [comment]
more data points, when I unwrap the response it is json

`{"code":"InvalidIdInRequest","message":"CredentialsV2Request: ID not found"}`

This is the same error returned by curl if I add/remove a character from the url path, but for the life of me I cannot figure out what is getting lost in the transmission.

**Comment by jonnymacs** [comment]
ok I have found the problem. I _think_ it is a bug in the Prorsum HTTPClient.

The GET request built by the RequestSerializer looks like this

```
GET http://169.254.170.2/v2/credentials/7a67e81e-c484-406e-8483-19a75f7b4f4a HTTP/1.1
Host: 169.254.170.2
User-Agent: curl/7.53.1
Accept: */*
Content-Length: 0
```

The request is built using `request.url.absoluteString` [(see this line)](https://github.com/noppoMan/Prorsum/blob/master/Sources/Prorsum/HTTP/Serializer/RequestSerializer.swift#L22)

This gets rejected with ID not found. If I use the `request.url.path` instead of `request.url.absoluteString`, then it works

```
GET /v2/credentials/7a67e81e-c484-406e-8483-19a75f7b4f4a HTTP/1.1
Host: 169.254.170.2
User-Agent: curl/7.53.1
Accept: */*
Content-Length: 0
```

If my interpretation of the HTTP/1.1 spec is correct [here](https://tools.ietf.org/html/rfc2616#section-5.1.2) then, the client should _not use_ `request.url.abosluteString` when the `request.host` is set as a header. But instead should use the `request.url.path`

**Comment by noppoMan** [comment]
@jonnymacs 
Sorry for late reply...
Thank you for your great consideration! I'll fix it in a few days.(I'm back from New Year holiday.)

**Comment by jonnymacs** [comment]
Hi Yuki,

Happy new year!

I have a fix on a fork for the prorsum project. You can look here
https://github.com/GetBlast/Prorsum at the branch 55_request_uri

Let me know what you think I can submit a pr today.

I am also wrapping up the support for this ticket on a fork in the core
project. It includes support for rereshing the token when it expires. I am
just adding some test coverage.

If you want to wait I will submit a pr for this as well by tomorrow?

Everything is working with my changes.

**Comment by noppoMan** [comment]
Happy new year!

I just looked https://github.com/GetBlast/Prorsum/commit/6519a8c067bc74909e6a0a68b8d530f3cac18eb7#diff-bdeeb16a5c55a7b1e40cbd97d371bed2.
It looks fine to me! So please submit the pr.(I found small coding violations, So I'll comment you on the pr thread)

> I am also wrapping up the support for this ticket on a fork in the core
project. It includes support for rereshing the token when it expires. I am
just adding some test coverage.
> If you want to wait I will submit a pr for this as well by tomorrow?

> Everything is working with my changes.

That would be great! I'm looking forward to see your changes. Please submit pr as well.

I'm so happy that you are using this library with enthusiasm.

**Comment by jonnymacs** [comment]
@noppoMan created a PR for this ticket. please let me know your thoughts!

https://github.com/noppoMan/aws-sdk-swift-core/pull/22

**Comment by noppoMan** [comment]
@jonnymacs 
I don't forget this! really sorry for late reply.

**Comment by jonnymacs** [comment]
@noppoMan chance to review? #22
